### ISSUE TITLE
Shapefile download results in invalid zip file

### ISSUE THREAD

**Issue by aubreymaemulawan** [altcoder/philippines-psgc-shapefiles#27]
## Description
I am experiencing an issue where the shapefile download appears to complete successfully, but when I attempt to open the zip file, it is reported as invalid or corrupted. This issue persists across different devices and on all (adm0, adm1, adm2, adm3, adm4) shapefile zip folders.

## Steps to reproduce
1. Navigate to the shapefile download section.
2. Download the shapefile zip file.
3. Attempt to open the downloaded zip file.

**Expected behavior**
The zip file should open successfully and contain a valid shapefile.

**Screenshots**
![image](https://github.com/user-attachments/assets/7a8e221f-b134-4cf7-beb6-85a40171878a)

## Versions

- Python:
- Node/NPM:
- Browser: Brave/Explorer

**Comment by MrGreyPH** [comment]
Im having the same issues. or maybe because im doing it wrong? I think Git LFS is required. Please let mw know if you have successfully used the files
